/run/initialize
/control/verbose  0
/run/verbose 0
/event/verbose    0
/tracking/verbose 0

###################################################
/gps/particle gamma
/gps/pos/type Beam
/gps/ene/type Mono
/gps/ene/mono 660. keV

/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1
/gps/pos/halfy 5 cm
/gps/pos/halfx 5 cm
/gps/pos/centre 0. 0. -50. cm

/gps/direction 0 0 1
###################################################
/run/beamOn 2000000